name: PHING
description: Run PHING

inputs:
  args:
    description: |
      Targets and Arguments to be passed to PHING
    required: true

runs:
  using: docker
  image: docker://elnebuloso/phing:4
  args:
    - phing
    - ${{ inputs.args }}