name: PHING
description: Run PHING

inputs:
  target:
    description: |
      Target to be passed to PHING
    required: true

runs:
  using: docker
  image: docker://elnebuloso/phing:4
  args:
    - phing
    - ${{ inputs.target }}