name: PHING
description: Run PHING

inputs:
  args:
    description: |
      Arguments to be passed to the phing
    required: true

runs:
  using: docker
  image: docker://elnebuloso/phing:4
  args:
    - ${{ inputs.args }}